### PR TITLE
Add functions for adding sparse factors/loadings to a flash object

### PR DESCRIPTION
**Pull request by willwerscheid**
Adds two new functions for adding sparse factors/loadings. Cleans up some documentation issues (in some function names, some uppercase letters were changed to lowercase, so the corresponding Rd files needed to be renamed as well).

### CODE REVIEW

**Comment by willwerscheid** [comment]
1. Sure, let's discuss. We do still have add_fixed_factor for cases where we want to add a complete (or nearly complete) factor. But I think there are two extremes: we have a sparse factor and initialize a few entries to zero (with no clue about what to do with the others) or we have a complete factor (from some other method) and don't need to worry so much about a few missing entries (so initialization via column means works fine). I would like to be convinced that there are some in-between cases that require both fixing some entries away from zero and clever initialization of the other entries.

2. Did you look at test_sparse?

3. Yes, I agree that that would be better.

**Comment by stephens999** [comment]
thanks - and sorry i missed the unit tests!

Regarding 1, I think the first issue we could try to agree on is terminology. (this is often the
most useful first step!)

Shall we use "fixed factor" to refer to a factor that has some elements fixed? Or only ones that have *all* elements fixed. I feel the former... the "all elements fixed" case is a trivial special case.
The alternative is to have two pieces of terminology - for example "supervised factor" is one that has some elements fixed and "fixed factor" is one that has all elements fixed. But for me that seems an unnecessary distinction.

Do you agree?

**Comment by willwerscheid** [comment]
Ok, I agree. And there's a difference between adding a sparse factor and adding a sparse factor in which a specified set of elements are fixed. So let's go with fixed.

Also I thought it about some more and I'm not sure we ever want to initialize using column means. If it fails when we're only trying to estimate a few non-null elements (and it does fail), then it will fail worse if we have a large number of elements we need to estimate. 

But there are 2 complications if we want to generalize the add_sparse functions I've written.

1. If there are in fact a large number of elements missing for each factor, then, because we need to loop from 1:K and call an SVD-type function at each iteration, performance could be very slow. (At each iteration, I'm calling the SVD function on a n_i x p matrix, where n_i is the number of elements missing.) If the same elements are missing in each case, we can of course speed this up by calling the SVD function once instead of K times. But if the user supplies a matrix where, say, the first third of elements are missing for factors 1,...,K/2 and the last third for factors K/2+1,...,K, then we will be in trouble again. We can check for block structures like this, but you can see that it begins to become complicated.

2. If the fixed factor elements are non-zero, then the initialization of the factor will be good, but the initialization of the loadings can be very poor. (This is not the case for sparse factors.) I haven't checked to see whether this makes a difference. That is, if you initialize f very close to the true value, and initialize l randomly, will you still find the "correct" l? I need to look into this.

Even with these limitations, though, I think the new functions (appropriately generalized) would be better than the old add_fixed functions, just because initializing using column means does not do well.

**Comment by willwerscheid** [comment]
Closing because I am rewriting these functions.

**Pull request closed without merging**
